name       : opencc
version    : 1.0.5
release    : 1
source     :
    - https://github.com/BYVoid/OpenCC/archive/ver.1.0.5.tar.gz : 1ce1649ba280cfc88bb76e740be5f54b29a9c034400c97a3ae211c37d7030705
license    : Apache-2.0
component  : programming.tools
summary    : A project for conversion between Traditional and Simplified Chinese
description: |
    A project for conversion between Traditional and Simplified Chinese
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
