name       : opencc
version    : 1.1.3
release    : 3
source     :
    - https://github.com/BYVoid/OpenCC/archive/refs/tags/ver.1.1.3.tar.gz : 99a9af883b304f11f3b0f6df30d9fb4161f15b848803f9ff9c65a96d59ce877f
license    : Apache-2.0
component  : programming.tools
summary    : A project for conversion between Traditional and Simplified Chinese
description: |
    A project for conversion between Traditional and Simplified Chinese
builddeps  :
    - pkgconfig(marisa)
    - pkgconfig(RapidJSON)
rundeps    :
    - rapidjson
setup      : |
    %cmake -DUSE_SYSTEM_MARISA=ON -DUSE_SYSTEM_RAPIDJSON=ON -L
build      : |
    %make
install    : |
    %make_install
