name       : opencc
version    : 1.1.4
release    : 4
source     :
    - https://github.com/BYVoid/OpenCC/archive/refs/tags/ver.1.1.4.tar.gz : ca33cf2a2bf691ee44f53397c319bb50c6d6c4eff1931a259fd11533ba26c1e9
license    : Apache-2.0
component  : programming.tools
summary    : A project for conversion between Traditional and Simplified Chinese
description: |
    A project for conversion between Traditional and Simplified Chinese
builddeps  :
    - pkgconfig(marisa)
    - pkgconfig(RapidJSON)
    - gtest-devel
rundeps    :
    - rapidjson
setup      : |
    %patch -p1 < $pkgfiles/Set-Soversion-Number-to-Project-Version.patch
    %cmake_ninja -DUSE_SYSTEM_MARISA=ON \
                 -DUSE_SYSTEM_RAPIDJSON=ON \
                 -DENABLE_GTEST=ON \
                 -DUSE_SYSTEM_GTEST=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
